name: Lint

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black mypy bandit

    - name: Lint with flake8
      run: | 
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        echo
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics